(source gnu)
(source melpa)
(source marmalade)

(package "mrb-emacs" "0.1.0" "MrB's Emacs configuration -- not a real package")

;; dependencies, i.e. which packages do I want to use in my config

(depends-on "stripe-buffer"         :git "https://github.com/sabof/stripe-buffer")
(depends-on "ace-jump-mode")
(depends-on "apache-mode")
(depends-on "async"                 :git "https://github.com/jwiegley/emacs-async")
(depends-on "autosmiley"            :git "https://github.com/emacsmirror/autosmiley")
(depends-on "btc-ticker"            :git "https://github.com/niedbalski/emacs-btc-ticker")
(depends-on "cl-lib")
(depends-on "company-mode"	    :git "https://github.com/company-mode/company-mode.git")
(depends-on "csv-mode")
(depends-on "cursor-chg"            :git "https://github.com/emacsmirror/cursor-chg")
(depends-on "dash"                  :git "https://github.com/magnars/dash.el")
(depends-on "edit-server")
(depends-on "elfeed"                :git "https://github.com/skeeto/elfeed")
(depends-on "erc-hl-nicks")
(depends-on "erc-image"             :git "https://github.com/mrvdb/erc-image.el")
(depends-on "erc-tweet"             :git "https://github.com/kidd/erc-tweet.el")
(depends-on "expand-region"         :git "https://github.com/magnars/expand-region.el")
(depends-on "f")
(depends-on "fixed-point-completion" :git "https://github.com/smithzvk/fixed-point-completion")
(depends-on "flycheck")
(depends-on "gh"                    :git "https://github.com/sigma/gh.el")
(depends-on "ghc-mod"               :git "https://github.com/kazu-yamamoto/ghc-mod" :files ("elisp/*.el"))
(depends-on "gist"                  :git "https://github.com/defunkt/gist.el")
(depends-on "git-auto-commit-mode"  :git "https://github.com/ryuslash/git-auto-commit-mode")
(depends-on "git-modes"		    :git "https://github.com/magit/git-modes.git")
(depends-on "git-messenger"         :git "https://github.com/syohex/emacs-git-messenger")
(depends-on "gnuplot-mode")
(depends-on "guide-key"             :git "https://github.com/kbkbkbkb1/guide-key")
(depends-on "haskell-mode")
(depends-on "hideshow-org")
(depends-on "highlight-parentheses")
(depends-on "identica-mode")
(depends-on "ido-vertical-mode")
(depends-on "jekyll-el"		    :git "https://github.com/diasjorge/jekyll.el.git")
(depends-on "json-rpc"              :git "https://github.com/skeeto/elisp-json-rpc")
(depends-on "keywiz")
(depends-on "logito"                :git "https://github.com/sigma/logito")
(depends-on "lua-mode"              :git "https://github.com/immerrr/lua-mode")
(depends-on "magit")
(depends-on "mark-multiple"         :git "https://github.com/magnars/mark-multiple.el")
(depends-on "markdown-mode")
(depends-on "metaweblog"            :git "https://github.com/punchagan/metaweblog.el")
(depends-on "multiple-cursors")
(depends-on "notmuch")
(depends-on "oauth"                 :git "https://github.com/psanford/emacs-oauth")
(depends-on "oauth")
(depends-on "scad-mode"              :git "https://github.com/openscad/openscad.git" :files ("contrib/*.el"))
(depends-on "org-agenda-property"   :git "https://github.com/Bruce-Connor/org-agenda-property")
(depends-on "org-jekyll")
(depends-on "org-present"           :git "https://github.com/rlister/org-present")
(depends-on "org-screenshot"        :git "https://github.com/dfeich/org-screenshot")
(depends-on "org2blog")
(depends-on "pcache"                :git "https://github.com/sigma/pcache")
(depends-on "perspective")
(depends-on "php-mode")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "s")
(depends-on "scratch")
(depends-on "smart-tab")
(depends-on "smex")
(depends-on "sudo-save"		    :git "https://github.com/emacsmirror/sudo-save.git")
(depends-on "ujelly-theme"          :git "https://github.com/marktran/color-theme-ujelly")
(depends-on "use-package")
(depends-on "wrap-region")
(depends-on "xlicense"              :git "https://github.com/emacsmirror/xlicense")
(depends-on "xml-rpc")
(depends-on "yaml-mode")
(depends-on "zenburn-theme"         :git "https://github.com/bbatsov/zenburn-emacs")
