(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auth-sources (quote ((:source "~/.authinfo" :host t :protocol t))))
 '(column-number-mode t)
 '(custom-safe-themes (quote ("ebb23762f3569b2d146b6091a6ed22cac44c4e53e8a33d9ff2bc3b90cc9e58e8" "819d81fabb0bde707a0f34cdd66e3bc1960273e8283e912a310e446ce3c44620" "363772e75d98d439856d08c013ae280ca55958db6ed073c43081ddba4404bef8" default)))
 '(custom-theme-load-path (quote ("/home/mrb/.emacs.d/el-get/" "/home/mrb/.emacs.d/el-get/zenburn-emacs/" custom-theme-directory t)))
 '(erc-modules (quote (autojoin button completion fill irccontrols keep-place list log match menu move-to-prompt netsplit networks noncommands readonly replace ring smiley stamp track unmorse)))
 '(flyspell-issue-message-flag nil)
 '(gud-gdb-command-name "gdb --annotate=1")
 '(ispell-use-framepop-p t)
 '(markdown-css-path "/home/mrb/.markdown.css")
 '(org-agenda-custom-commands (quote (("w" "Waiting For list" tags-todo "-inactive/WAITING" ((org-agenda-overriding-header "WAITING FOR-list") (org-agenda-view-columns-initially t) (org-agenda-overriding-columns-format "%65ITEM %Responsible %SCHEDULED %TAGS") (org-agenda-dim-blocked-tasks t))) ("b" "Buying list" tags-todo "+buy-inactive-TODO=\"DONE\"-TODO=\"CANCELLED\"" ((org-agenda-overriding-header "Buying list") (org-agenda-dim-blocked-tasks t) (org-agenda-group-by-property "BLOCKED"))) ("p" "Active project list" tags-todo "-inactive+LEVEL>1-TODO=\"DONE\"-TODO=\"CANCELLED\"" ((org-agenda-overriding-header "Active project list") (org-agenda-skip-function (quote mrb/skip-non-projects)) (org-agenda-dim-blocked-tasks nil) (org-agenda-group-by-property "CATEGORY") (org-agenda-sorting-strategy (quote (alpha-up))))) ("A" "Active task list" tags-todo "-BLOCKED=\"t\"+SCHEDULED=\"\"-inactive/TODO" ((org-agenda-group-by-property "CATEGORY"))) ("r" "To Review" ((tags-todo "SCHEDULED=\"\"+DEADLINE=\"\"-{.}-BLOCKED=\"t\"/TODO" ((org-agenda-overriding-header "Untagged items"))) (tags-todo "-inactive+SCHEDULED=\"\"+DEADLINE=\"\"-BLOCKED=\"t\"+TODO=\"TODO\"+{.}" ((org-agenda-overriding-header "Unscheduled active items")))) nil) ("S" "Someday/Maybe List" ((tags "+inactive" ((org-agenda-overriding-header "Inactive projects") (org-agenda-skip-function (quote mrb/skip-non-projects)))) (tags-todo "+inactive-BLOCKED=\"t\"/TODO" ((org-agenda-overriding-header "Inactive TODO items")))) nil nil) ("c" "Scheduled overview" tags-todo "SCHEDULED<>\"\"|DEADLINE<>\"\"/TODO" ((org-agenda-overriding-header "SCHEDULED") (org-agenda-view-columns-initially t) (org-agenda-overriding-columns-format "%65ITEM %25Responsible %SCHEDULED %DEADLINE %TAGS") (org-agenda-dim-blocked-tasks t))) ("l" "Blocked projects and tasks" ((tags-todo "+BLOCKED=\"t\"/PROJ" ((org-agenda-overriding-header "Blocked projects") (org-agenda-dim-blocked-tasks t))) (tags-todo "+BLOCKED=\"t\"/TODO" ((org-agenda-overriding-header "Blocked tasks") (org-agenda-dim-blocked-tasks t) (org-agenda-group-by-property "CATEGORY")))) nil nil) ("n" "Next Action List [hides blocked/inactive/waiting/INBOX-ed]" tags-todo "+SCHEDULED=\"\"+DEADLINE=\"\"-BLOCKED=\"t\"-inactive/-WAITING" ((org-agenda-overriding-header "Next Action List") (org-agenda-group-by-property "CREATED"))) ("g" "AGENDA" agenda "" ((org-agenda-filter-preset (quote ("-inactive"))) (org-agenda-span (quote day)))) ("x" "List of stuck projects (debug)" tags "-inactive+LEVEL>1-TODO=\"DONE\"-TODO=\"CANCELLED\"" ((org-agenda-skip-function (quote mrb/skip-non-stuck-projects)) (org-agenda-overriding-header "List of STUCK projects"))))))
 '(org-agenda-files (quote ("~/.outlet/GTD.org" "~/.outlet/orgmode.org" "~/.outlet/cobra.org" "~/.outlet/habits.org" "~/.outlet/meetings.org" "~/.outlet/blogs.org" "~/.outlet/keuken.org")))
 '(org-alphabetical-lists t)
 '(org-blocker-ignore-ancestor-siblings t)
 '(org-export-docbook-xsl-fo-proc-command "fop %i %o")
 '(org-export-docbook-xslt-proc-command "xsltproc --output %o %s %i")
 '(org-export-htmlize-output-type (quote css))
 '(org-export-htmlized-org-css-url "orgmode.css")
 '(org-export-latex-classes (quote (("article" "\\documentclass[11pt,a4paper,twoside]{article}" ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection{%s}" . "\\subsubsection*{%s}") ("\\paragraph{%s}" . "\\paragraph*{%s}") ("\\subparagraph{%s}" . "\\subparagraph*{%s}")) ("report" "\\documentclass[11pt]{report}" ("\\part{%s}" . "\\part*{%s}") ("\\chapter{%s}" . "\\chapter*{%s}") ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection{%s}" . "\\subsubsection*{%s}")) ("book" "\\documentclass[11pt]{book}" ("\\part{%s}" . "\\part*{%s}") ("\\chapter{%s}" . "\\chapter*{%s}") ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection{%s}" . "\\subsubsection*{%s}")) ("beamer" "\\documentclass{beamer}" org-beamer-sectioning))))
 '(org-export-latex-hyperref-format "\\ref{%s}:{%s}")
 '(org-export-latex-title-command "")
 '(org-mobile-agendas (quote default))
 '(org-mobile-use-encryption nil t)
 '(org-plantuml-jar-path "/home/mrb/dev/emacs/packages/org-mode/contrib/scripts/plantuml.jar")
 '(org-stuck-projects (quote ("-inactive/+TODO" ("TODO" "WAITING") nil "")))
 '(org-tags-exclude-from-inheritance (quote ("area" "encrypt")))
 '(org-time-stamp-custom-formats (quote ("<%m/%d/%y %a>" . "<%H:%M>")))
 '(org-toodledo-inhibit-https nil)
 '(org-toodledo-sync-new-completed-tasks t)
 '(org-toodledo-sync-on-save "no")
 '(show-paren-mode t)
 '(statusnet-access-url "http://o.mrblog.nl/api/oauth/access_token")
 '(statusnet-authorize-url "http://o.mrblog.nl/api/oauth/authorize")
 '(statusnet-request-url "http://o.mrblog.nl/api/oauth/request_token")
 '(tab-always-indent (quote complete))
 '(typopunct-buffer-language (quote english)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#303030" :foreground "#dcdccc" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "microsoft" :family "Consolas"))))
 '(flyspell-duplicate ((t (:foreground "goldenrod" :underline t :weight bold))) t)
 '(flyspell-incorrect ((t (:foreground "tomato" :underline t :weight bold))) t)
 '(identica-stripe-face ((t (:inherit font-lock-string :background "gray25"))) t)
 '(lazy-highlight ((t (:inherit isearch-lazy-highlight :background "dark slate gray"))))
 '(org-agenda-date ((t (:inherit org-agenda-structure :height 1.2))) t)
 '(org-agenda-date-today ((t (:foreground "white" :slant italic :weight bold :height 1.2))) t)
 '(org-agenda-structure ((t (:inherit font-lock-comment-face :weight bold :height 1.1))))
 '(org-column ((t (:strike-through nil :underline nil :slant normal :weight normal :height 98 :family "Consolas"))))
 '(org-date ((t (:foreground "#8cd0d3" :underline nil))))
 '(org-document-info ((((class color) (background light)) (:inherit org-date))))
 '(org-headline-done ((t (:foreground "#afd8af" :weight bold))))
 '(org-property-value ((t (:height 0.85))) t)
 '(org-sexp-date ((t (:height 0.85))))
 '(org-special-keyword ((t (:height 0.85)))))

